# Generated by Django 5.1 on 2024-09-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pustakalay_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('lang', 'Languages'), ('webdev', 'Web Development'), ('dbms', 'DBMS'), ('ai/ml', 'AI/ML'), ('CS', 'Cyber Security'), ('iot', 'IOT'), ('dsa', 'DSA'), ('Others', 'Others')], default='Others', max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='publish',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='libraryuser',
            name='photo',
            field=models.FileField(default='/default_image.jpeg', upload_to='profile_pic/'),
        ),
    ]
