# Generated by Django 5.0.7 on 2024-09-27 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('fileID', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('file', models.FileField(default=None, upload_to='Media/book')),
                ('fileDescription', models.TextField()),
                ('author', models.CharField(max_length=40)),
                ('public', models.DateTimeField()),
                ('category', models.CharField(max_length=30)),
                ('rating', models.IntegerField(default=0)),
                ('reting_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryUser',
            fields=[
                ('userid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=6)),
                ('fileID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pb_app.documents')),
            ],
        ),
        migrations.AddField(
            model_name='documents',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pb_app.libraryuser'),
        ),
    ]
